### PR TITLE
Discord Bot Slash Command Bug Fix

### PR DESCRIPTION
**Pull request by SwingTheVine**
Added a bug fix for the slash commands to buy server resources.

### CODE REVIEW

**Review by Nagol12344 — APPROVED** [review]
Looks good! PR title could have been better, but quick fix. Thanks!

**Comment by SwingTheVine** [comment]
There you go!

**Comment by Nagol12344** [comment]
ehhhhh, ok.

**Comment by The-MG** [comment]
I will take a look next time I have a chance. Looks hopeful.

**Comment by The-MG** [comment]
Would it be possible to have this PR closed and open another one with the same fix but on cav4?

**Comment by SwingTheVine** [comment]
Moved to #16

**Pull request closed without merging**
